
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class Inscricao
{

    public int IdInscricao { get; set; }

    public string NumeroSocio { get; set; }

    public string DataInscricao { get; set; }

    public string DataRevalidacao { get; set; }

    public string DataRevalidacaoAnterior { get; set; }

    public string DataExameMedico { get; set; }

    public string Estado { get; set; }

}

}
