
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class inscricoes
{

    public int id_inscricao { get; set; }

    public string numero_socio { get; set; }

    public string data_inscricao { get; set; }

    public string data_revalidacao { get; set; }

    public string data_exame_medico { get; set; }

    public string estado { get; set; }

}

}
