
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class InscricaoJudo
{

    public int IdInscricaoJudo { get; set; }

    public int IdInscricao { get; set; }

    public int LicencaFederativa { get; set; }



    public virtual Inscricao Inscricao { get; set; }

    public virtual EscalaoJudo EscalaoJudo { get; set; }

}

}
