
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class Inscricao
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Inscricao()
    {

        this.Participacao = new HashSet<Participacao>();

        this.InscricaoJudo = new HashSet<InscricaoJudo>();

        this.InscricaoJiujitsu = new HashSet<InscricaoJiujitsu>();

        this.InscricaoAikido = new HashSet<InscricaoAikido>();

    }


    public int IdInscricao { get; set; }

    public string NumeroSocio { get; set; }

    public string DataInscricao { get; set; }

    public string DataRevalidacao { get; set; }

    public string DataRevalidacaoAnterior { get; set; }

    public string DataExameMedico { get; set; }

    public string Estado { get; set; }



    public virtual Socios Socios { get; set; }

    public virtual Exame Exame { get; set; }

    public virtual Arbitro Arbitro { get; set; }

    public virtual Treinadores Treinadores { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Participacao> Participacao { get; set; }

    public virtual ResultadoCompeticao ResultadoCompeticao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InscricaoJudo> InscricaoJudo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InscricaoJiujitsu> InscricaoJiujitsu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InscricaoAikido> InscricaoAikido { get; set; }

}

}
