

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModelDiagramaBDContainer : DbContext
{
    public ModelDiagramaBDContainer()
        : base("name=ModelDiagramaBDContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Socios> SociosSet { get; set; }

    public virtual DbSet<Inscricao> InscricaoSet { get; set; }

    public virtual DbSet<Entidades> EntidadesSet { get; set; }

    public virtual DbSet<Quotas> QuotasSet { get; set; }

    public virtual DbSet<TipoPagamento> TipoPagamentoSet { get; set; }

    public virtual DbSet<InscricaoJudo> InscricaoJudoSet { get; set; }

    public virtual DbSet<InscricaoJiujitsu> InscricaoJiujitsuSet { get; set; }

    public virtual DbSet<InscricaoAikido> InscricaoAikidoSet { get; set; }

    public virtual DbSet<EscalaoJudo> EscalaoJudoSet { get; set; }

    public virtual DbSet<EscalaoJiujitsu> EscalaoJiujitsuSet { get; set; }

    public virtual DbSet<EscalaoAikido> EscalaoAikidoSet { get; set; }

    public virtual DbSet<Treinadores> TreinadoresSet { get; set; }

    public virtual DbSet<Arbitro> ArbitroSet { get; set; }

    public virtual DbSet<Exame> ExameSet { get; set; }

    public virtual DbSet<Graduacao> GraduacaoSet { get; set; }

    public virtual DbSet<Participacao> ParticipacaoSet { get; set; }

    public virtual DbSet<Nivel> NivelSet { get; set; }

    public virtual DbSet<Competicao> CompeticaoSet { get; set; }

    public virtual DbSet<ResultadoCompeticao> ResultadoCompeticaoSet { get; set; }

}

}

