

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ModelDiagramaBDContainer : DbContext
{
    public ModelDiagramaBDContainer()
        : base("name=ModelDiagramaBDContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<socios> sociosSet { get; set; }

    public virtual DbSet<inscricoes> inscricoesSet { get; set; }

    public virtual DbSet<socios_quotas> socios_quotasSet { get; set; }

    public virtual DbSet<entidades_quotas> entidades_quotasSet { get; set; }

    public virtual DbSet<quotas> quotasSet { get; set; }

    public virtual DbSet<tipo_pagamento> tipo_pagamentoSet { get; set; }

    public virtual DbSet<entidades> entidadesSet { get; set; }

    public virtual DbSet<entidades_telefones> entidades_telefonesSet { get; set; }

    public virtual DbSet<socios_telefone> socios_telefoneSet { get; set; }

    public virtual DbSet<telefones> telefonesSet { get; set; }

}

}

