
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class Participacao
{

    public int IdParticipacao { get; set; }

    public string Localidade { get; set; }

    public string Descricao { get; set; }

    public string Data { get; set; }

    public string Nivel { get; set; }

}

}
