
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class Quotas
{

    public int NumeroQuota { get; set; }

    public string Descricao { get; set; }

    public int Valor { get; set; }

    public System.DateTime Data { get; set; }



    public virtual Socios Socios { get; set; }

    public virtual TipoPagamento TipoPagamento { get; set; }

    public virtual Entidades Entidades { get; set; }

}

}
