
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class quotas
{

    public int numero_quota { get; set; }

    public string descricao { get; set; }

    public string valor { get; set; }

    public string data { get; set; }

    public string tipo_pagamento { get; set; }



    public virtual tipo_pagamento tipo_pagamento1 { get; set; }

    public virtual entidades_quotas entidades_quotas { get; set; }

}

}
