
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class ResultadoCompeticao
{

    public int IdResultadoCompeticao { get; set; }

    public string IdInscricao { get; set; }

    public string Classificacao { get; set; }

    public string Pontos { get; set; }

}

}
