
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrototipoFuncionalClubeDeJudoDragao
{

using System;
    using System.Collections.Generic;
    
public partial class socios
{

    public string numero_socio { get; set; }

    public string nome { get; set; }

    public string morada { get; set; }

    public string codigo_postal { get; set; }

    public string localidade { get; set; }

    public string data_nascimento { get; set; }

    public string nif { get; set; }

    public string numero_cc { get; set; }

    public string data_emissao_cc { get; set; }

    public string nacionalidade { get; set; }

    public string profissao { get; set; }

    public string freguesia { get; set; }

    public string concelho { get; set; }

    public string sexo { get; set; }

    public string estado_civil { get; set; }

}

}
